global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
  - job_name: rustfs-job
    metrics_path: /metrics
    scheme: http
    static_configs:
        - targets: ['rustfs:9000']
